name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Check Generic8266(ESP-01)
        # TODO: add  --fail-on-defect medium when all medium errors are fixed
        run: |
          pio check -e ESP8266-ESP01 --fail-on-defect high

      - name: Check WEMOS_D1_Mini
        # TODO: add  --fail-on-defect medium when all medium errors are fixed
        run: |
          pio check -e WEMOS_D1_Mini --fail-on-defect high

      - name: Check ESP32DEV
        # TODO: add  --fail-on-defect medium when all medium errors are fixed
        run: |
          pio check -e ESP32DEV --fail-on-defect high
